In [ ]:
import pandas as pd
from pathlib import Path

file_path = Path(r"C:\Users\Anjali\OneDrive\Desktop\VBS KPMG DAY3\hugging_face.csv")

df = pd.read_csv(file_path)
    
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

Dataset shape: (6000, 16)

Column names:
['Customer_ID', 'review_text', 'sentiment_label', 'satisfaction_score', 'preferred_category', 'preferred_channel', 'customer_value_segment', 'customer_tenure_months', 'orders_last_12m', 'days_since_last_purchase', 'support_tickets_12m', 'return_rate', 'churn', 'purchase_next_30_days', 'data_origin', 'split']

In [24]:
df.head()

,Customer_ID,review_text,sentiment_label,satisfaction_score,preferred_category,preferred_channel,customer_value_segment,customer_tenure_months,orders_last_12m,days_since_last_purchase,support_tickets_12m,return_rate,churn,purchase_next_30_days,data_origin,split
0,CUST009609,I am unhappy with my Sports & Fitness order an...,negative,2.00,Sports & Fitness,Website,Low Value,26,8,84,4,0.190,1,0,synthetic_generated_for_training,train
1,CUST004601,I was disappointed with my Electronics purchas...,negative,1.56,Electronics,Mobile App,Medium Value,10,7,63,4,0.000,1,1,synthetic_generated_for_training,test
2,CUST000722,I was disappointed with my Sports & Fitness pu...,negative,1.89,Sports & Fitness,Website,Low Value,12,6,73,6,0.119,1,0,synthetic_generated_for_training,train
3,CUST007179,The Books shopping experience needs improvemen...,negative,2.41,Books,Physical Store,Low Value,12,4,322,0,0.210,1,0,synthetic_generated_for_training,train
4,CUST002160,"My Sports & Fitness order was frustrating, and...",negative,2.46,Sports & Fitness,Marketplace,Medium Value,20,6,36,2,0.327,0,1,synthetic_generated_for_training,validation

In [2]:
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist)

Dataset shape: (6000, 16)

Column names:
<bound method IndexOpsMixin.tolist of Index(['Customer_ID', 'review_text', 'sentiment_label', 'satisfaction_score',
       'preferred_category', 'preferred_channel', 'customer_value_segment',
       'customer_tenure_months', 'orders_last_12m', 'days_since_last_purchase',
       'support_tickets_12m', 'return_rate', 'churn', 'purchase_next_30_days',
       'data_origin', 'split'],
      dtype='str')>

In [3]:
print("\nFirst five reviews")
display(df[['review_text', 'sentiment_label', 'split']].head())

First five reviews

,review_text,sentiment_label,split
0,I am unhappy with my Sports & Fitness order an...,negative,train
1,I was disappointed with my Electronics purchas...,negative,test
2,I was disappointed with my Sports & Fitness pu...,negative,train
3,The Books shopping experience needs improvemen...,negative,train
4,"My Sports & Fitness order was frustrating, and...",negative,validation

In [4]:
print("\nSentiment distribution:")
print(df["sentiment_label"].value_counts())

Sentiment distribution:
sentiment_label
positive    3287
neutral     1988
negative     725
Name: count, dtype: int64

In [5]:
print("\nMissing review text:", df["review_text"].isna().sum())
print("Missing sentiment labels:", df["sentiment_label"].isna().sum())

Missing review text: 0
Missing sentiment labels: 0

In [ ]:
%pip install transformers torch

Defaulting to user installation because normal site-packages is not writeable
Collecting transformers
  Using cached transformers-5.19.0-py3-none-any.whl.metadata (32 kB)
Collecting torch
  Using cached torch-2.14.1-cp313-cp313-win_amd64.whl.metadata (38 kB)
Collecting huggingface-hub<3.0,>=1.31.0 (from transformers)
  Using cached huggingface_hub-2.2.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy>=1.17 in c:\programdata\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\programdata\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from transformers) (2026.9.29)
Collecting tokenizers<0.24.0,>=0.23.1 (from transformers)
  Using cached tokenizers-0.23.3-cp310-abi3-win_amd64.whl.metadata (10 kB)
Requirement already satisfied: typer in c:\programdata\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\programdata\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.7.0)
Collecting httpx2<3,>=2.0.0 (from huggingface-hub<3.0,>=1.31.0->transformers)
  Using cached httpx2-2.13.1-py3-none-any.whl.metadata (9.8 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Collecting anyio>=4.10 (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers)
  Using cached anyio-4.15.1-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: httpcore2==2.13.1 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (2.13.1)
Requirement already satisfied: idna>=3.18 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Requirement already satisfied: truststore>=0.10 in c:\programdata\anaconda3\lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.10.0)
Requirement already satisfied: h11>=0.16 in c:\programdata\anaconda3\lib\site-packages (from httpcore2==2.13.1->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from torch) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\programdata\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\programdata\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.60->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)
Using cached transformers-5.19.0-py3-none-any.whl (12.6 MB)
Using cached huggingface_hub-2.2.0-py3-none-any.whl (839 kB)
Using cached httpx2-2.13.1-py3-none-any.whl (95 kB)
Using cached tokenizers-0.23.3-cp310-abi3-win_amd64.whl (2.9 MB)
Using cached torch-2.14.1-cp313-cp313-win_amd64.whl (124.1 MB)
Using cached anyio-4.15.1-py3-none-any.whl (132 kB)
Installing collected packages: anyio, torch, httpx2, huggingface-hub, tokenizers, transformers

   ---------------------------------------- 0/6 [anyio]
   ---------------------------------------- 0/6 [anyio]
   ---------------------------------------- 0/6 [anyio]
   ---------------------------------------- 0/6 [anyio]
   ---------------------------------------- 0/6 [anyio]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]
   ------ --------------------------------- 1/6 [torch]

  WARNING: The scripts torchfrtrace.exe and torchrun.exe are installed in 'C:\Users\Anjali\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script httpx2.exe is installed in 'C:\Users\Anjali\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts hf.exe and tiny-agents.exe are installed in 'C:\Users\Anjali\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script transformers.exe is installed in 'C:\Users\Anjali\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [ ]:
from transformers import pipeline

MODEL_NAME = "cardiffnlp/twitter-roberta-base-sentiment-latest"

sentiment_analyzer = pipeline(
    task="sentiment-analysis",
    model=MODEL_NAME
)

ModuleNotFoundError: No module named 'transformers'

In [ ]:
import sys
print(sys.executable)

%pip show transformers

c:\ProgramData\anaconda3\python.exe
Name: transformers
Version: 5.19.0
Summary: Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, for both inference and training.
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages
Requires: huggingface-hub, numpy, packaging, pyyaml, regex, safetensors, tokenizers, tqdm, typer
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import sys
!{sys.executable} -m pip install transformers torch

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in c:\users\anjali\appdata\roaming\python\python313\site-packages (5.19.0)
Requirement already satisfied: torch in c:\users\anjali\appdata\roaming\python\python313\site-packages (2.14.1)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from transformers) (2.2.0)
Requirement already satisfied: numpy>=1.17 in c:\programdata\anaconda3\lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\programdata\anaconda3\lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from transformers) (2026.9.29)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from transformers) (0.23.3)
Requirement already satisfied: typer in c:\programdata\anaconda3\lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.8.0 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\programdata\anaconda3\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\programdata\anaconda3\lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2.13.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Requirement already satisfied: anyio>=4.10 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Requirement already satisfied: httpcore2==2.13.1 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (2.13.1)
Requirement already satisfied: idna>=3.18 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Requirement already satisfied: truststore>=0.10 in c:\programdata\anaconda3\lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.10.0)
Requirement already satisfied: h11>=0.16 in c:\programdata\anaconda3\lib\site-packages (from httpcore2==2.13.1->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: setuptools>=77.0.3 in c:\users\anjali\appdata\roaming\python\python313\site-packages (from torch) (84.0.0)
Requirement already satisfied: sympy>=1.13.3 in c:\programdata\anaconda3\lib\site-packages (from torch) (1.13.3)
Requirement already satisfied: networkx>=2.5.1 in c:\programdata\anaconda3\lib\site-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in c:\programdata\anaconda3\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.60->transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2->torch) (3.0.2)

In [ ]:
from transformers import pipeline

MODEL_NAME = "cardiffnlp/twitter-roberta-base-sentiment-latest"

sentiment_analyzer = pipeline(
    task="sentiment-analysis",
    model=MODEL_NAME
)

ModuleNotFoundError: No module named 'transformers'

In [ ]:
import sys
print("Notebook Python:", sys.executable)

!{sys.executable} -m pip install --upgrade pip
!{sys.executable} -m pip install transformers

Notebook Python: c:\ProgramData\anaconda3\python.exe
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in c:\programdata\anaconda3\lib\site-packages (25.1)
Collecting pip
  Using cached pip-26.2.1-py3-none-any.whl.metadata (4.6 kB)
Using cached pip-26.2.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
Successfully installed pip-26.2.1

  WARNING: The scripts pip.exe, pip3.13.exe and pip3.exe are installed in 'C:\Users\Anjali\AppData\Roaming\Python\Python313\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (5.19.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from transformers) (2.2.0)
Requirement already satisfied: numpy>=1.17 in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from transformers) (2026.9.29)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from transformers) (0.23.3)
Requirement already satisfied: typer in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.8.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2.13.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Requirement already satisfied: anyio>=4.10 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Requirement already satisfied: httpcore2==2.13.1 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (2.13.1)
Requirement already satisfied: idna>=3.18 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Requirement already satisfied: truststore>=0.10 in c:\ProgramData\anaconda3\Lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.10.0)
Requirement already satisfied: h11>=0.16 in c:\ProgramData\anaconda3\Lib\site-packages (from httpcore2==2.13.1->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: colorama in c:\ProgramData\anaconda3\Lib\site-packages (from tqdm>=4.60->transformers) (0.4.6)

In [ ]:
import sys
import subprocess

print("Python:", sys.executable)

subprocess.run([
    sys.executable, "-m", "pip", "show", "transformers"
])

Python: c:\ProgramData\anaconda3\python.exe

CompletedProcess(args=['c:\\ProgramData\\anaconda3\\python.exe', '-m', 'pip', 'show', 'transformers'], returncode=0)

In [ ]:
import sys
import subprocess

result = subprocess.run(
    [sys.executable, "-m", "pip", "show", "transformers"],
    capture_output=True,
    text=True
)

print(result.stdout)
print(result.stderr)
print("Exit code:", result.returncode)

Name: transformers
Version: 5.19.0
Summary: Transformers: the model-definition framework for state-of-the-art machine learning models in text, vision, audio, and multimodal models, for both inference and training.
Home-page: https://github.com/huggingface/transformers
Author: The Hugging Face team (past and future) with the help of all our contributors (https://github.com/huggingface/transformers/graphs/contributors)
Author-email: transformers@huggingface.co
License: Apache 2.0 License
Location: C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages
Requires: huggingface-hub, numpy, packaging, pyyaml, regex, safetensors, tokenizers, tqdm, typer
Required-by:


Exit code: 0

In [ ]:
import sys
!{sys.executable} -m pip install transformers

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (5.19.0)
Requirement already satisfied: huggingface-hub<3.0,>=1.31.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from transformers) (2.2.0)
Requirement already satisfied: numpy>=1.17 in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from transformers) (2026.9.29)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from transformers) (0.23.3)
Requirement already satisfied: typer in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (0.9.0)
Requirement already satisfied: safetensors>=0.8.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in c:\ProgramData\anaconda3\Lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in c:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (3.17.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\ProgramData\anaconda3\Lib\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2025.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (1.7.0)
Requirement already satisfied: httpx2<3,>=2.0.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (2.13.1)
Requirement already satisfied: typing-extensions>=4.1.0 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from huggingface-hub<3.0,>=1.31.0->transformers) (4.16.0)
Requirement already satisfied: anyio>=4.10 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (4.15.1)
Requirement already satisfied: httpcore2==2.13.1 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (2.13.1)
Requirement already satisfied: idna>=3.18 in C:\Users\Anjali\AppData\Roaming\Python\Python313\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (3.20)
Requirement already satisfied: truststore>=0.10 in c:\ProgramData\anaconda3\Lib\site-packages (from httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.10.0)
Requirement already satisfied: h11>=0.16 in c:\ProgramData\anaconda3\Lib\site-packages (from httpcore2==2.13.1->httpx2<3,>=2.0.0->huggingface-hub<3.0,>=1.31.0->transformers) (0.16.0)
Requirement already satisfied: colorama in c:\ProgramData\anaconda3\Lib\site-packages (from tqdm>=4.60->transformers) (0.4.6)

In [ ]:
! pip install transformers

Access is denied.

In [9]:
from transformers import pipeline

print("Transformers imported successfully!")

c:\Users\Anjali\.conda\envs\regression_app\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Transformers imported successfully!

In [12]:
from transformers import pipeline

print("Transformers imported successfully!")

Transformers imported successfully!

In [13]:
from transformers import pipeline

MODEL_NAME = "cardiffnlp/twitter-roberta-base-sentiment-latest"

sentiment_analyzer = pipeline(
    task="sentiment-analysis",
    model=MODEL_NAME
)

print("Sentiment model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
c:\Users\Anjali\.conda\envs\regression_app\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Anjali\.cache\huggingface\hub\models--cardiffnlp--twitter-roberta-base-sentiment-latest. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
c:\Users\Anjali\.conda\envs\regression_app\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Anjali\.cache\huggingface\hub. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Loading weights: 100%|██████████| 201/201 [00:00<00:00, 15174.05it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: cardiffnlp/twitter-roberta-base-sentiment-latest
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Sentiment model loaded successfully!

In [14]:
test_reviews =[
    "The product quality is excellent and delivery was first",
    "The product arrived damaged and customer support was helpful.",
    "The package arrived yesterday."
]

for review in test_reviews:
    result = sentiment_analyzer(review)[0]

    print("Review:", review)
    print("sentiment:", result['label'])
    print("score:", round(result['score'], 4))
    print("_" * 60)

Review: The product quality is excellent and delivery was first
sentiment: positive
score: 0.9724
____________________________________________________________
Review: The product arrived damaged and customer support was helpful.
sentiment: neutral
score: 0.4172
____________________________________________________________
Review: The package arrived yesterday.
sentiment: neutral
score: 0.5292
____________________________________________________________

In [18]:

print("Dataset split distribution:")
print(df["split"].value_counts())

print("\nSentiment labels:")
print(df["sentiment_label"].value_counts())

Dataset split distribution:
split
train         4800
test           600
validation     600
Name: count, dtype: int64

Sentiment labels:
sentiment_label
positive    3287
neutral     1988
negative     725
Name: count, dtype: int64

In [23]:

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# Select held-out test data only
test_df = df.loc[
    df["split"].str.lower() == "test",
    ["review_text", "sentiment_label"]
].dropna().copy()

print("Test records:", len(test_df))

# Predict in batches
predictions = sentiment_analyzer(
    test_df["review_text"].astype(str).tolist(),
    batch_size=16,
    truncation=True
)
test_df["predicted_sentiment"] = [
    p["label"].lower()  for p in predictions
]

Test records: 600